  GNU nano 8.4                                                                                    docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: venucms_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: venu-web
    container_name: venucms_fastapi
    environment:
      DB_HOST: venucms_postgres  # Make sure the DB_HOST is set correctly
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: venucms_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
