

services:
  db:
    image: postgres:15
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    container_name: ${PROJECT_NAME}_fastapi
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"  # Nginx orqali ulanish uchun
    command: >
      sh -c "uvicorn run:app --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"  # HTTP (80-port)
      - "443:443"  # HTTPS (443-port) faqat so'rovni qabul qiladi, lekin SSL talab qilinmaydi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro


volumes:
  pg_data:


