# --- HTTP (Redirect to HTTPS) ---
server {
    listen 80;
    server_name venuapi.cims.cognilabs.org;


    # Redirect all HTTP -> HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

